/* Generated By:JavaCC: Do not edit this line. TokenizerConstants.java */
package tokenize;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TokenizerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TAG = 1;
  /** RegularExpression Id. */
  int TAG_WORD = 2;
  /** RegularExpression Id. */
  int TAG_EXIT = 3;
  /** RegularExpression Id. */
  int DQTAG_ATTR = 4;
  /** RegularExpression Id. */
  int SQTAG_ATTR = 5;
  /** RegularExpression Id. */
  int TAG_MISC = 6;
  /** RegularExpression Id. */
  int DQATTR_WORD = 7;
  /** RegularExpression Id. */
  int DQATTR_EXIT = 8;
  /** RegularExpression Id. */
  int DQATTR_MISC = 9;
  /** RegularExpression Id. */
  int SQATTR_WORD = 10;
  /** RegularExpression Id. */
  int SQATTR_EXIT = 11;
  /** RegularExpression Id. */
  int SQATTR_MISC = 12;
  /** RegularExpression Id. */
  int CHAR = 13;
  /** RegularExpression Id. */
  int WORD = 14;
  /** RegularExpression Id. */
  int NUMBER = 15;
  /** RegularExpression Id. */
  int MISC = 20;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_TAG = 1;
  /** Lexical state. */
  int IN_DQATTR = 2;
  /** Lexical state. */
  int IN_SQATTR = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"<\"",
    "<TAG_WORD>",
    "\">\"",
    "\"\\\"\"",
    "\"\\\'\"",
    "<TAG_MISC>",
    "<DQATTR_WORD>",
    "\"\\\"\"",
    "<DQATTR_MISC>",
    "<SQATTR_WORD>",
    "\"\\\'\"",
    "<SQATTR_MISC>",
    "<CHAR>",
    "<WORD>",
    "<NUMBER>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<MISC>",
  };

}
